/*
Oliver Kahn
Ylessanne01
06.12.2023
*/

// Andmete salvestamine muutujatesse
var data1 = 4.2;
var data2 = 'Will Code 4 food';
var data3 = "123";
var data4 = true;
var data5 = [1, 2, 3];
var data6 = false;
var data7 = 'true';
var data8 = undefined;

// Andmete tüüpide väljastamine konsooli
console.log("Andme1 tüüp: " + typeof data1);
console.log("Andme2 tüüp: " + typeof data2);
console.log("Andme3 tüüp: " + typeof data3);
console.log("Andme4 tüüp: " + typeof data4);
console.log("Andme5 tüüp: " + typeof data5);
console.log("Andme6 tüüp: " + typeof data6);
console.log("Andme7 tüüp: " + typeof data7);
console.log("Andme8 tüüp: " + typeof data8);